import type { LeadAnalysis } from '../types/lead'
import type { Priority } from '../types/lead'

/**
 * LeadAnalysisCard
 *
 * Displays the complete structured AI analysis returned by Gemini.
 * Rendered in a clean 2-column grid layout for high readability.
 */
export default function LeadAnalysisCard({ analysis }: { analysis: LeadAnalysis }) {
  return (
    <div className="rounded-xl border border-violet-200 bg-white shadow-sm">
      {/* ── Header ──────────────────────────────────────────── */}
      <div className="flex items-center gap-3 rounded-t-xl border-b border-violet-100 bg-violet-50 px-6 py-4">
        <span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg bg-accent">
          <svg
            className="h-4 w-4 text-white"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9.663 17h4.673M12 3v1m6.364 1.636-.707.707M21 12h-1M4 12H3m3.343-5.657-.707-.707m2.828 9.9a5 5 0 1 1 7.072 0l-.548.547A3.374 3.374 0 0 0 14 18.469V19a2 2 0 1 1-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
            />
          </svg>
        </span>
        <div className="flex-1">
          <h3 className="text-sm font-semibold text-accent">AI Lead Analysis</h3>
          <p className="text-xs text-text-muted">
            Generated by Gemini · Structured sales intelligence
          </p>
        </div>
        {/* Priority badge in header */}
        <PriorityBadge priority={analysis.priority} score={analysis.priorityScore} />
      </div>

      {/* ── Priority detail row ───────────────────────────────── */}
      <div className={`border-b border-violet-100 px-6 py-3 ${priorityBg(analysis.priority)}`}>
        <div className="flex items-center justify-between">
          <div>
            <p className={`text-xs font-semibold uppercase tracking-widest ${priorityLabel(analysis.priority)}`}>
              {analysis.priority} Priority
            </p>
            <p className="mt-0.5 text-xs text-text-muted">
              Score: {analysis.priorityScore} / 100
            </p>
          </div>
          {/* Score bar */}
          <div className="w-32">
            <div className="h-2 w-full overflow-hidden rounded-full bg-border">
              <div
                className={`h-2 rounded-full ${priorityBarColor(analysis.priority)}`}
                style={{ width: `${analysis.priorityScore}%` }}
              />
            </div>
            <p className="mt-0.5 text-right text-xs text-text-muted">
              {scoreLabel(analysis.priority)}
            </p>
          </div>
        </div>
      </div>

      {/* ── 2-Column Information Layout ───────────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6">
        {/* Left Column */}
        <div className="space-y-5">
          <Section title="Lead Summary">
            <p className="text-sm leading-relaxed text-text bg-surface p-3.5 rounded-lg border border-border">
              {analysis.leadSummary}
            </p>
          </Section>

          <Section title="Customer Intent">
            <p className="text-sm leading-relaxed text-text bg-surface p-3.5 rounded-lg border border-border">
              {analysis.customerIntent}
            </p>
          </Section>

          <Section title="Key Requirements">
            <div className="bg-surface p-3.5 rounded-lg border border-border">
              <BulletList items={analysis.keyRequirements} />
            </div>
          </Section>
        </div>

        {/* Right Column */}
        <div className="space-y-5">
          <Section title="Objections / Concerns">
            <div className="bg-surface p-3.5 rounded-lg border border-border">
              <BulletList items={analysis.objectionsConcerns} empty="No specific concerns identified." />
            </div>
          </Section>

          <Section title="Recommended Next Action">
            <div className="rounded-lg border border-primary/20 bg-blue-50/70 p-3.5">
              <p className="text-sm font-semibold leading-relaxed text-primary">
                ⚡ {analysis.recommendedNextAction}
              </p>
            </div>
          </Section>

          <Section title="Suggested Response">
            <div className="rounded-lg border border-border bg-surface p-3.5">
              <p className="text-sm italic leading-relaxed text-text-secondary">
                "{analysis.suggestedResponse}"
              </p>
            </div>
          </Section>
        </div>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Priority helpers
// ---------------------------------------------------------------------------

function priorityBg(p: Priority): string {
  return p === 'HOT' ? 'bg-red-50' : p === 'WARM' ? 'bg-amber-50' : 'bg-slate-50'
}

function priorityLabel(p: Priority): string {
  return p === 'HOT' ? 'text-red-700' : p === 'WARM' ? 'text-amber-700' : 'text-slate-600'
}

function priorityBarColor(p: Priority): string {
  return p === 'HOT' ? 'bg-red-500' : p === 'WARM' ? 'bg-amber-500' : 'bg-slate-400'
}

function scoreLabel(p: Priority): string {
  return p === 'HOT' ? 'Follow up now' : p === 'WARM' ? 'Nurture lead' : 'Low urgency'
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function PriorityBadge({ priority, score }: { priority: Priority; score: number }) {
  const styles: Record<Priority, string> = {
    HOT:  'bg-red-100 border-red-300 text-red-700',
    WARM: 'bg-amber-100 border-amber-300 text-amber-700',
    COLD: 'bg-slate-100 border-slate-300 text-slate-600',
  }
  return (
    <span
      className={`flex-shrink-0 rounded-full border px-3 py-1 text-xs font-bold ${styles[priority]}`}
    >
      {priority} {score}/100
    </span>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h4 className="mb-2 text-xs font-semibold uppercase tracking-widest text-text-muted">
        {title}
      </h4>
      {children}
    </div>
  )
}

function BulletList({ items, empty = 'None identified.' }: { items: string[]; empty?: string }) {
  if (!items || items.length === 0) {
    return <p className="text-sm text-text-muted">{empty}</p>
  }
  return (
    <ul className="space-y-1.5">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-text">
          <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-accent" />
          <span className="leading-relaxed">{item}</span>
        </li>
      ))}
    </ul>
  )
}

