import type { LeadAnalysis } from '../types/lead'
import type { Priority } from '../types/lead'

/**
 * LeadAnalysisCard
 *
 * Displays structured AI analysis returned by Gemini.
 * Rendered in a clean 2-column grid layout for high readability.
 */
export default function LeadAnalysisCard({ analysis }: { analysis: LeadAnalysis }) {
  return (
    <div className="rounded-xl border border-violet-200 bg-white shadow-sm overflow-hidden">
      {/* ── Header Row ──────────────────────────────────────── */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-violet-100 bg-violet-50/80 px-6 py-4">
        <div className="flex items-center gap-3">
          <span className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-lg bg-violet-600 text-white shadow-sm">
            <svg
              className="h-5 w-5"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9.663 17h4.673M12 3v1m6.364 1.636-.707.707M21 12h-1M4 12H3m3.343-5.657-.707-.707m2.828 9.9a5 5 0 1 1 7.072 0l-.548.547A3.374 3.374 0 0 0 14 18.469V19a2 2 0 1 1-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
              />
            </svg>
          </span>
          <div>
            <h3 className="text-base font-bold text-violet-950">AI Lead Analysis</h3>
            <p className="text-xs font-semibold text-slate-600">
              Generated by Gemini · Structured sales intelligence
            </p>
          </div>
        </div>

        {/* Priority Status Pill */}
        <div className="flex items-center gap-2">
          <span className={`rounded-full px-3 py-1 text-xs font-extrabold uppercase tracking-wider ${priorityBadgeStyle(analysis.priority)}`}>
            {analysis.priority} Priority
          </span>
        </div>
      </div>

      {/* ── Priority Status Bar ──────────────────────────────── */}
      <div className={`border-b border-violet-100 px-6 py-2.5 ${priorityBg(analysis.priority)}`}>
        <div className="flex items-center justify-between text-xs">
          <span className={`font-extrabold uppercase tracking-widest ${priorityLabel(analysis.priority)}`}>
            {analysis.priority} PRIORITY · SCORE {analysis.priorityScore}/100
          </span>
          <span className="font-bold text-slate-700">
            {scoreLabel(analysis.priority)}
          </span>
        </div>
      </div>

      {/* ── 2-Column Information Layout ───────────────────────── */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6">
        {/* Left Column */}
        <div className="space-y-5">
          <Section title="Lead Summary">
            <p className="text-sm leading-relaxed font-medium text-slate-900 bg-slate-50 p-3.5 rounded-lg border border-slate-200">
              {analysis.leadSummary}
            </p>
          </Section>

          <Section title="Customer Intent">
            <p className="text-sm leading-relaxed font-medium text-slate-900 bg-slate-50 p-3.5 rounded-lg border border-slate-200">
              {analysis.customerIntent}
            </p>
          </Section>

          <Section title="Key Requirements">
            <div className="bg-slate-50 p-3.5 rounded-lg border border-slate-200">
              <BulletList items={analysis.keyRequirements} />
            </div>
          </Section>
        </div>

        {/* Right Column */}
        <div className="space-y-5">
          <Section title="Objections / Concerns">
            <div className="bg-slate-50 p-3.5 rounded-lg border border-slate-200">
              <BulletList items={analysis.objectionsConcerns} empty="No specific concerns identified." />
            </div>
          </Section>

          <Section title="Recommended Next Action">
            <div className="rounded-lg border border-blue-200 bg-blue-50/90 p-3.5 shadow-sm">
              <div className="flex items-start gap-2">
                <svg className="h-4 w-4 text-blue-600 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
                </svg>
                <p className="text-sm font-bold leading-relaxed text-blue-950">
                  {analysis.recommendedNextAction}
                </p>
              </div>
            </div>
          </Section>

          <Section title="Suggested Response">
            <div className="rounded-lg border border-slate-200 bg-slate-50 p-3.5">
              <p className="text-sm font-semibold italic leading-relaxed text-slate-900">
                "{analysis.suggestedResponse}"
              </p>
            </div>
          </Section>
        </div>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Priority helpers
// ---------------------------------------------------------------------------

function priorityBadgeStyle(p: Priority): string {
  return p === 'HOT'
    ? 'bg-red-100 text-red-800 border border-red-200'
    : p === 'WARM'
    ? 'bg-amber-100 text-amber-800 border border-amber-200'
    : 'bg-slate-100 text-slate-800 border border-slate-200'
}

function priorityBg(p: Priority): string {
  return p === 'HOT' ? 'bg-red-50' : p === 'WARM' ? 'bg-amber-50' : 'bg-slate-50'
}

function priorityLabel(p: Priority): string {
  return p === 'HOT' ? 'text-red-700' : p === 'WARM' ? 'text-amber-700' : 'text-slate-700'
}

function scoreLabel(p: Priority): string {
  return p === 'HOT' ? 'Urgent follow up required' : p === 'WARM' ? 'Active lead nurture' : 'Standard priority'
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h4 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-700">
        {title}
      </h4>
      {children}
    </div>
  )
}

function BulletList({ items, empty = 'None identified.' }: { items: string[]; empty?: string }) {
  if (!items || items.length === 0) {
    return <p className="text-sm font-medium text-slate-500">{empty}</p>
  }
  return (
    <ul className="space-y-1.5">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm font-medium text-slate-900">
          <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-violet-600" />
          <span className="leading-relaxed">{item}</span>
        </li>
      ))}
    </ul>
  )
}


